openapi: 3.0.0
info:
  title: Contract collection
  description: collects contracts with all important information
  version: 0.1.0
servers:
  - url: 'http://localhost:8080/demo'
paths:
  /add:
    post:
      summary: creates a new contract
      operationId: addContract
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_GEN_00"
                          - "RC_ADD_00"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
        401:
          description: "NOT FOUND"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_ADD_10"
                          - "RC_GEN_99"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
  /delete:
    post:
      summary: deletes a contract
      operationId: deleteContract
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_DEL_00"
                          - "RC_GEN_00"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
        400:
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_DEL_20"
                          - "RC_GEN_99"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
        422:
          description: "UNPROCESSABLE ENTITY"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_DEL_10"
                          - "RC_GEN_99"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
  /all:
    get:
      summary: fetches all contracts
      operationId: getAllContracts
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_GEN_00"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
  /get:
    get:
      summary: fetches one specific contract
      operationId: getSingleContract
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_GEN_00"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
  /change:
    patch:
      summary: updates a contract
      operationId: updateContract
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_UPD_00"
                          - "RC_GEN_00"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'
        409:
          description: "CONFLICT"
          content:
            application/json:
              schema:
                type: object
                properties:
                  head:
                    type: object
                    properties:
                      message:
                        type: string
                        description: response message with further information
                      reasonCode:
                        type: string
                        enum:
                          - "RC_UPD_10"
                          - "RC_GEN_99"
                        description: provides basic information on the action result
                  body:
                    $ref: '#/components/schemas/contractJson'

components:
  schemas:
    contractJson:
      type: object
      properties:
        category:
          type: string
          description: determines the category of a contract
        name:
          type: string
          description: some name for the user
        expenses:
          type: number
          format: float
          description: expenses per payment
        cycle:
          type: integer
          minimum: 1
          description: number of payments per year
        customerNr:
          type: string
          description: id of customer
        contractNr:
          type: string
          description: id of the contract
        startdate:
          type: string
          description: start of the contract in format "YYYY-MM-DD"
        contractPeriod:
          type: integer
          description: length of a contractual period
        periodOfNotice:
          type: integer
          description: number of weeks when the contract can be noticed at last before end of a contractual period
        description:
          type: string
          description: a short description of the contract
        documentPath:
          type: string
          description: place where the important files are located