name: backend-CI
on:
  - push
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Test with TestNG
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: -b build.gradle test

  docs:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: make gradlew runnable
        run: chmod +x ./gradlew

      - name: create API documentation
        run: |
          ./gradlew openApiGenerate
          rm -r build/docs/openapi/.openapi-generator && rm build/docs/openapi/.openapi-generator-ignore

      - name: create javadoc documentation
        run: ./gradlew javadoc

      - name: upload docs to artifact
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: Backend/build/docs
          retention-days: 1