name: backend-CI
on:
  - push
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: --spring.profiles.active=prod assemble
          build-root-directory: Backend

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Test with TestNG
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: --spring.profiles.active=prod test
          build-root-directory: Backend


  docs:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
        working-directory: Backend

    steps:
      - name: make gradlew runnable
        run: chmod +x ./gradlew

      - name: create API documentation
        run: |
          ./gradlew openApiGenerate
          rm -r build/docs/openapi/.openapi-generator && rm build/docs/openapi/.openapi-generator-ignore
          ./gradlew generateSwaggerUIBackend
          rm build/docs/swaggerUI-Backend/index.html && mv build/docs/swaggerUI-Backend/swaggerUI.html build/docs/swaggerUI-Backend/index.html

      - name: create javadoc documentation
        run: ./gradlew javadoc

      - name: create jacoco documentation
        run: ./gradlew test

      - name: upload docs to artifact
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: Backend/build/docs
          retention-days: 1