name: Dependency submissions
on:
  - pull_request

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          overwrite-settings: false

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          gradle-version: 8.6
          build-root-directory: Backend
          dependency-graph-continue-on-failure: true