name: Dependency submissions
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          dependency-graph-continue-on-failure: true
          additional-arguments: '--stacktrace'